name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main # or master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 💎 Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: 🧐 Check _posts directory
        run: |
          echo "Contents of blog/_posts:"
          ls -la blog/_posts/

      - name: 🛠️ Build the Jekyll site
        run: |
          bundle install
          bundle exec jekyll build --destination _site

      - name: 📂 Check _site directory contents
        run: |
          echo "Contents of _site:"
          ls -la _site

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
          commit_message: "Deploy new site version from GitHub Actions"